version: 2.1

orbs:
    hmpps: ministryofjustice/hmpps@3.13
    slack: circleci/slack@4.4.2

parameters:
    node-version:
        type: string
        default: 14.17-browsers
    alerts-slack-channel:
        type: string
        default: hmpps_tech_alerts_security

jobs:
    build:
        executor:
            name: hmpps/node
            tag: << pipeline.parameters.node-version >>
        steps:
            - checkout
            - run:
                  name: Update npm
                  command: 'sudo npm install -g npm@6.14.8'
            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                  name: Install Dependencies
                  command: npm ci --no-audit
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules
            - run:
                  name: Linter
                  command: npm run lint

    unit_test:
        executor:
            name: hmpps/node
            tag: << pipeline.parameters.node-version >>
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                name: unit tests
                command: |
                    npm run test -- --exit
                    npm run snyk-protect
            - store_test_results:
                path: test_results
            - store_artifacts:
                path: test-results/unit-test-reports.html

    deploy:
        executor:
            name: hmpps/node
            tag: << pipeline.parameters.node-version >>
        parameters:
            push-to-branch:
                description: >
                    Specify the branch that will be pushed to. Azure Web Apps webhook monitors this branch
                    and will deploy from it when it is triggered.
                default: "azure-stage"
                type: string
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - deploy:
                  name: Build Derived Git Commit
                  command: |
                    BUILD_NUMBER=$CIRCLE_BUILD_NUM \
                    GIT_REF=$CIRCLE_SHA1 \
                        npm run record-build-info
                    git add --force --verbose build-info.json
                    git config user.name "Circle CI"
                    git config user.email "circle@circleci.com"
                    CI_MESSAGE=$(git log --format=%B -n 1 $CIRCLE_SHA1)
                    git commit -m "Deployment of build $CIRCLE_BUILD_NUM" -m "$CI_MESSAGE" -m "From gitref $CIRCLE_SHA1"
            - deploy:
                  name: Deploy to Stage Environment
                  command: git push --force origin "HEAD:<< parameters.push-to-branch >>"

workflows:
    version: 2
    build-test-and-deploy:
        jobs:
            - build:
                filters:
                    tags:
                        ignore: /.*/
            - unit_test:
                requires:
                    - build
            - deploy:
                name: deploy_stage
                push-to-branch: "azure-stage"
                requires:
                    - unit_test
                filters:
                    branches:
                        only:
                            - main
            - request-preprod-approval:
                type: approval
                requires:
                    - deploy_stage
            - deploy:
                  name: deploy_preprod
                  push-to-branch: "azure-preprod"
                  requires:
                      - request-preprod-approval
            - request-prod-approval:
                type: approval
                requires:
                    - deploy_preprod
            - deploy:
                name: deploy_prod
                push-to-branch: "azure-prod"
                requires:
                    - request-prod-approval

    security:
        triggers:
            - schedule:
                  cron: "30 5 * * 1-5"
                  filters:
                      branches:
                          only:
                              - main
        jobs:
            - hmpps/npm_security_audit:
                  slack_channel: << pipeline.parameters.alerts-slack-channel >>
                  context:
                      - hmpps-common-vars
