generic-service:
  replicaCount: 2

  ingress:
    host: hpa-dev.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://hpa-dev.prison.service.justice.gov.uk"
    CALLBACK_URL: "https://hpa-dev.prison.service.justice.gov.uk/authentication"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_HOST: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_HOST: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    DB_NAME: "iis-dev"

  scheduledDowntime:
    enabled: true
    startup: '22 6 * * 1-5' # Start at 6.22am UTC Monday-Friday
    shutdown: '52 21 * * 1-5' # Stop at 9.52pm UTC Monday-Friday

generic-prometheus-alerts:
  alertSeverity: syscon-nonprod
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-ddb6945a92970e78: "historical prisoner"
