generic-service:
  replicaCount: 2

  ingress:
    host: hpa-preprod.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://hpa-preprod.prison.service.justice.gov.uk"
    CALLBACK_URL: "https://hpa-preprod.prison.service.justice.gov.uk/authentication"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_HOST: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_HOST: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PROD
    DB_NAME: "iis-stage"

generic-prometheus-alerts:
  alertSeverity: syscon-nonprod
