generic-service:
  ingress:
    host: hpa.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://hpa.prison.service.justice.gov.uk"
    CALLBACK_URL: "https://hpa.prison.service.justice.gov.uk/authentication"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_HOST: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_HOST: "https://manage-users-api.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    DB_NAME: "iis-prod"

  allowlist:
    groups:
      - internal
      - prisons

generic-prometheus-alerts:
  alertSeverity: syscon
  rdsAlertsDatabases:
    cloud-platform-7cf4b6d00ff4674a: "historical prisoner"
