generic-service:
  replicaCount: 2

  ingress:
    host: hpa-preprod.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://hpa-preprod.prison.service.justice.gov.uk"
    CALLBACK_URL: "https://hpa-preprod.prison.service.justice.gov.uk/authentication"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_HOST: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_HOST: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PROD
    DB_NAME: "iis-preprod"

  scheduledDowntime:
    enabled: true
    startup: '50 6 * * 1-5' # Start at 6.50am UTC Monday-Friday
    shutdown: '50 20 * * 1-5' # Stop at 8.50pm UTC Monday-Friday

generic-prometheus-alerts:
  alertSeverity: syscon-nonprod
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-4bdb6c77965e5153: "historical prisoner"
